### ISSUE TITLE
@lighthousebot in private repos?

### ISSUE THREAD

**Issue by schoenwaldnils** [ebidel/lighthouse-ci#15]
Hi, I added @lighthousebot in a private repository. (about a week ago)
But the collaboration didn't get accepted yet.
Is this possible, or does this need a human to accept it? ^^

**Comment by ebidel** [comment]
A human. Can you send the invite again? I may have missed it.

**Comment by schoenwaldnils** [comment]
@ebidel done

**Comment by ebidel** [comment]
Ah, it's because your settings require the bot to have 2-factor enabled on the account.

**Comment by schoenwaldnils** [comment]
Does this mean it doesn't work the lighthousebot?

**Comment by ebidel** [comment]
Most likely no? I don't plan on enabling 2 factor auth on that account (it's a shared account). So if that prevents you from adding it to your repo, than it won't be able to modify PR comments.
