### ISSUE TITLE
Inline Render blocking scripts

### ISSUE THREAD

**Issue by KathiresanRamkumar95** [ebidel/lighthouse-ci#17]
How to get time taken by the inline render blocking scripts time.
I wrote tiny inline scripts in my HTML file. I want to know the scripting time and the scripts block the parsing of the html? I am trying to know the scripting time of the inline script. But I cant the chrome dev tool takes inline scripting as parsing.

**Comment by ebidel** [comment]
This should be asked/filed over on the main lighthouse project: https://github.com/GoogleChrome/lighthouse

**Comment by KathiresanRamkumar95** [comment]
Is there any possible way to get the report from lighthouse during Gitlab CI.
