### ISSUE TITLE
Lighthouse Bot in Enterprise (Private) Repos?

### ISSUE THREAD

**Issue by scoobycoder** [ebidel/lighthouse-ci#22]
Hello,

Kudos to your for building this.  I'm trying to use this inside my company's Git Enterprise repo.  It's protected with LDAP / AD based logins.  Lighthouse bot does not have an account at my company. :)  Is there anything I can do to use Lighthouse CI without lighthouse bot?

Thanks!

Nate

**Comment by ebidel** [comment]
For custom setups like this, I recommend running your own docker container/endpoint.

https://github.com/ebidel/lighthouse-ci#running-your-own-ci-server
