### ISSUE TITLE
Adding it to the market place 

### ISSUE THREAD

**Issue by RobertJGabriel** [ebidel/lighthouse-ci#3]
Hey,
 Quick question more than anything else. Any plans for making this a full on bot instead of a user?

**Comment by RobertJGabriel** [comment]
Nevermind saw the part about the GitHub payload at the bottom of the readme :) If you need any help just shout

**Comment by ebidel** [comment]
Yea, right now this gives users the most flexibility to test with and for us to iterate to see what works. I proper integration would be ideal, but that also comes with a level of readiness :)

I also want to encourage folks to [run their own CI endpoint](https://github.com/ebidel/lighthouse-ci#running-your-own-ci-server). Hopefully the code in this repo makes that trivial for others to setup.
