### ISSUE TITLE
Thresholds

### ISSUE THREAD

**Issue by ebidel** [ebidel/lighthouse-ci#37]
Allow users to specify failure thresholds for each report category. Right now it's purely based off the PWA scores.

**Comment by addyosmani** [comment]
After chatting with @ebidel, he's graciously offered to try landing support for a flag/threshold for each category of audit (e.g. performance). This enables failing a build if performance isn't within a budget.
This would unblock us recommending lighthouse-ci in a tutorial @mihajlija is working on 🎉 

We also briefly discussed getting behind a single source of truth config (e.g budgets.json/thresholds.json) file. For now we're going to add the flags and switch over to config once it comes around. We might try reusing what we choose to do over in https://github.com/GoogleChrome/lighthouse/issues/6053.

**Comment by ebidel** [comment]
Can we assume that if any category score fails, the whole PR fails?

Examples:
 
```
 // get 90 on perf => fail
lighthouse-ci --performance=95 https://example.com

 // get 95 on perf => pass
lighthouse-ci --performance=95 https://example.com

/ / get 96 on perf, 92 on pwa => fail
lighthouse-ci --pwa=93 --performance=95 https://example.com 
```

**Comment by addyosmani** [comment]
I think it's pretty fair for the whole PR to fail if any category score fails.
