### ISSUE TITLE
Other options in json data on CURL -X POST request ?

### ISSUE THREAD

**Issue by BlackPearl01** [ebidel/lighthouse-ci#39]
Hello,

Thanks for your tool !

In your readme you're talking about the possibility to make a curl request (curl -X POST...). In this request, we have two parameters, "url" and "format".

I would like to know if we can provide other parameters? For example, can we increase the screenshot resolution preview or can we specify the user-agent? 

Thanks!

**Comment by ebidel** [comment]
`url` and `format` are the only options forwarded on to Lighthouse ATM. However, you're welcome to fork the codebase and expand upon it.
