### ISSUE TITLE
Status Checks Never Sent

### ISSUE THREAD

**Issue by ggennrich** [ebidel/lighthouse-ci#43]
I have followed the instructions but we never get status checks attached to the PR. I can see the results in Travis (along with subsequent failure since it didn't meet thresholds) but that's it. The bot is a collaborator on our private repo and new accounts don't force 2FA. Any ideas what I'm doing wrong?

Appreciate the work you have done on this project!

**Comment by ebidel** [comment]
IIRC, private repos are an issue. Are you able to see updates with a public
repo?

**Comment by ggennrich** [comment]
Wow I'm an idiot. I installed it via yarn `yarn add lighthouse-ci` which is an entirely different repo of the same name. Clearly I did not follow the instructions. Sorry to waste your time!
