### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by lukasoppermann** [ebidel/lighthouse-ci#6]
Hey when I try to run it I get the following error:

```
/Users/lukasoppermann/Code/veare/node_modules/lighthouse-ci/runlighthouse.js:100
    owner: repoSlug.split('/')[0],
```

I just installed it locally using npm, I hope that is fine. Am I doing something wrong or is that a legit bug? Can I somehow provide more info?

**Comment by Siilwyn** [comment]
What is the environment variable `TRAVIS_PULL_REQUEST_SLUG` set to?

**Comment by lukasoppermann** [comment]
Ohh, well, I just ran it locally, does this not work? Basically what I want to do is run it on travis but test it locally on travis so start up a node server on travis and test it.

I know it is not advised but I basically just want to get notified if my score gets worse which should be fine with a local version.

**Comment by Siilwyn** [comment]
I don't fully understand your reply but if you run it on Travis it should work.

**Comment by ebidel** [comment]
Right, the script needs to be run on Travis. Actually it should be telling you that: https://github.com/ebidel/lighthouse-ci/blob/master/runlighthouse.js#L148

If you want to test against a local backend, you can specify the [`CI_HOST` env variable.](https://github.com/ebidel/lighthouse-ci/blob/master/runlighthouse.js#L21) Point it at your local server.
