### ISSUE TITLE
How long does it take to send the key?

### ISSUE THREAD

**Issue by abdonrd** [ebidel/lighthouse-ci#9]
How long does it take to send the key?

https://github.com/ebidel/lighthouse-ci#get-an-api-key

Thanks in advance!

**Comment by ebidel** [comment]
Sent

**Comment by mresti** [comment]
Hi @ebidel ,

How long does it take to send the key? I'd sent the request.

Thanks in advance!!

**Comment by ebidel** [comment]
Within a week. I have a backlog right now. Working on Chrome Dev Summit
stuff for next week :)
